# Generated by Django 2.0.13 on 2019-10-07 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_prbac.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_prbac', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='django_prbac.Role')),
                ('role_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='django_prbac.Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(django_prbac.models.ValidatingModel, models.Model),
        ),
    ]
